project:
  type: website
  output-dir: docs
  render: 
    - absence.qmd
    - attainment_extra.qmd
    - about.qmd

website:
  title: "Brighton and Hove Secondary Schools Consultation Evidence"
  navbar:
    background: primary
    search: true
  sidebar:
    style: "docked"
    search: true
    contents:
      - text: "About"
        href: about.qmd
      - section: "Analysis"
        contents: 
          - absence.qmd
          - attainment_extra.qmd
        
    tools:
      - icon: person-circle
        href: https://adamdennett.co.uk
      - icon: twitter
        href: https://twitter.com/adam_dennett
      - icon: github
        menu:
          - text: Source Code
            url:  https://github.com/adamdennett/BH_Schools_Consultation
          - text: Report a Bug
            url:  https://github.com/adamdennett/BH_Schools_Consultation/issues
  repo-url: https://github.com/adamdennett/BH_Schools_Consultation
  repo-actions: [source, issue]
  google-analytics: "G-CE74LTF9B1"
  open-graph: true
  twitter-card: true

format:
  html:
    theme: journal
    css: styles.css
    toc: true
    code-fold: true
    code-tools: true

editor: visual

