---
title: "free_bus_pt3"
author: "Adam Dennett"
---


```{r Setup-Libraries, echo=FALSE, message=FALSE, warning=FALSE, error=FALSE, include=FALSE, results='hide'}
library(tidyr)
library(dplyr)
library(writexl)
library(tidyverse)
library(here)
library(janitor)
library(sf)
library(usethis)
library(tmap)
library(readxl)
library(r5r)
library(RColorBrewer)
library(accessibility)
library(data.table)
library(ggplot2)
library(interp)
library(h3jsr)
library(h3r)
library(osmextract)
library(stplanr)
library(od)
library(tidytransit)
library(gtsf)
library(DBI)
library(RPostgreSQL)
library(RPostgres)
library(rpostgis)
library(leaflet)
library(dplyr)

memory.limit(size = 32000)  # Increase to 16 GB

```

```{r get-schools-info, warning=FALSE, message=FALSE, echo=FALSE}
# Read the GeoPackage
BN_pcds_to_school_dist <- st_read("data/BN_pcds_to_school_dist.gpkg") %>%   st_transform(4326)

brighton_sec_schools <- read_csv("https://www.dropbox.com/scl/fi/fhzafgt27v30lmmuo084y/edubasealldata20241003.csv?rlkey=uorw43s44hnw5k9js3z0ksuuq&raw=1") %>% 
  clean_names() %>% 
  filter(la_name == "Brighton and Hove") %>% 
  filter(phase_of_education_name == "Secondary") %>% 
  filter(establishment_status_name == "Open") %>%
  st_as_sf(., coords = c("easting", "northing")) %>% 
  st_set_crs(27700) %>% 
  st_transform(4326) %>% 
  st_set_crs(4326)

bh_sec_sch <- brighton_sec_schools %>% 
  select(urn, establishment_name, geometry) %>%
  rename(id = urn)

coords <- st_coordinates(bh_sec_sch)
bh_sec_sch$lon <- coords[, 1]
bh_sec_sch$lat <- coords[, 2]

```

## Blatchington Mill - Free Travel Area

```{r warning=FALSE, message=FALSE, echo=FALSE}
# Blatchington Mill School (114606)
bh_sec_sch_114606 <- bh_sec_sch %>% filter(id == "114606")

subset_cost <- BN_pcds_to_school_dist %>% filter(total_cost < 4828.03)
subset_free <- BN_pcds_to_school_dist %>% filter(total_cost > 4828.03)

blatchington_bus_cost <- subset_cost %>% filter(destination_id == 114606)
blatchington_bus_free <- subset_free %>% filter(destination_id == 114606)

map_blatchington <- leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolylines(data = blatchington_bus_free, 
               color = "#9e0142", 
               weight = 2, 
               opacity = 0.3) %>%
  addPolylines(data = blatchington_bus_cost, 
               color = "#3288bd", 
               weight = 2, 
               opacity = 0.3) %>%
  addCircleMarkers(data = bh_sec_sch_114606, 
                   ~lon, ~lat, 
                   color = "black", 
                   radius = 4,  
                   weight = 2,  
                   fillOpacity = 1,
                   popup = ~establishment_name)

map_blatchington

```

## Hove Park - Free Travel Area

```{r warning=FALSE, message=FALSE, echo=FALSE}
# Hove Park School and Sixth Form Centre (114607)
bh_sec_sch_114607 <- bh_sec_sch %>% filter(id == "114607")

subset_cost <- BN_pcds_to_school_dist %>% filter(total_cost < 4828.03)
subset_free <- BN_pcds_to_school_dist %>% filter(total_cost > 4828.03)

hovepark_bus_cost <- subset_cost %>% filter(destination_id == 114607)
hovepark_bus_free <- subset_free %>% filter(destination_id == 114607)

map_hovepark <- leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolylines(data = hovepark_bus_free, 
               color = "#9e0142", 
               weight = 2, 
               opacity = 0.3) %>%
  addPolylines(data = hovepark_bus_cost, 
               color = "#3288bd", 
               weight = 2, 
               opacity = 0.3) %>%
  addCircleMarkers(data = bh_sec_sch_114607, 
                   ~lon, ~lat, 
                   color = "black", 
                   radius = 4,  
                   weight = 2,  
                   fillOpacity = 1,
                   popup = ~establishment_name)

map_hovepark

```

## Kings School - Free Travel Area

```{r warning=FALSE, message=FALSE, echo=FALSE}
# King's School (139409)
bh_sec_sch_139409 <- bh_sec_sch %>% filter(id == "139409")

subset_cost <- BN_pcds_to_school_dist %>% filter(total_cost < 4828.03)
subset_free <- BN_pcds_to_school_dist %>% filter(total_cost > 4828.03)

kings_bus_cost <- subset_cost %>% filter(destination_id == 139409)
kings_bus_free <- subset_free %>% filter(destination_id == 139409)

map_kings <- leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolylines(data = kings_bus_free, 
               color = "#9e0142", 
               weight = 2, 
               opacity = 0.3) %>%
  addPolylines(data = kings_bus_cost, 
               color = "#3288bd", 
               weight = 2, 
               opacity = 0.3) %>%
  addCircleMarkers(data = bh_sec_sch_139409, 
                   ~lon, ~lat, 
                   color = "black", 
                   radius = 4,  
                   weight = 2,  
                   fillOpacity = 1,
                   popup = ~establishment_name)

map_kings

```

## PACA - Free Travel Area

```{r warning=FALSE, message=FALSE, echo=FALSE}
# Portslade Aldridge Community Academy (137063)
bh_sec_sch_137063 <- bh_sec_sch %>% filter(id == "137063")

subset_cost <- BN_pcds_to_school_dist %>% filter(total_cost < 4828.03)
subset_free <- BN_pcds_to_school_dist %>% filter(total_cost > 4828.03)

paca_bus_cost <- subset_cost %>% filter(destination_id == 137063)
paca_bus_free <- subset_free %>% filter(destination_id == 137063)

map_paca <- leaflet() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addPolylines(data = paca_bus_free, 
               color = "#9e0142", 
               weight = 2, 
               opacity = 0.3) %>%
  addPolylines(data = paca_bus_cost, 
               color = "#3288bd", 
               weight = 2, 
               opacity = 0.3) %>%
  addCircleMarkers(data = bh_sec_sch_137063, 
                   ~lon, ~lat, 
                   color = "black", 
                   radius = 4,  
                   weight = 2,  
                   fillOpacity = 1,
                   popup = ~establishment_name)

map_paca

```

